version: '2'

services:

  dta:
    image: moresandeep/milagro-incubator:0.1
    ports:
      - "8001:8001"
    command: /dta.sh --address=0.0.0.0

  rps:
    image: moresandeep/milagro-incubator:0.1
    ports:
      - "8011:8011"
    command: /rps.sh --address=0.0.0.0 --DTALocalURL=http://dta:8001 --rpsBaseURL="" --RPAVerifyUserURL=http://mpinDemo:8005/mpinVerify

  mpinDemo:
    image: moresandeep/milagro-incubator:0.1
    ports:
      - "8005:8005"
    command: /mpinDemo.sh --address=0.0.0.0 --RPSURL=http://rps:8011 --mpinJSURL=http://mpin.miracl.com/v4/mpin.js
